config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en|vi/ do
    resources :books
    root to: "static_pages#home"
    get "static_pages/list_books"
    get "sessions/login"
    post "sessions/login" ,to: "sessions#create"
    delete "sessions/logout", to: "sessions#destroy"
    get "sessions/sign_up"

    resources :users do
        resources :borrowing_books
    end

    namespace :admin do
        root to:
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :current_user

  def home
    @abc = Book.order_by_title
                 .paginate(page: params[:page],
                  per_page: Settings.static_page.per_page)
  end

  def list_books
    @categories = Category.all
    @books = check_params.includes(:author, :category)
                         .paginate(page: params[:page],
                          per_page: Settings.static_page.per_page)
    if @books.empty?
      flash[:info] = "Không tìm thấy sách #{params[:term]}"

    end
  end

  private

  def check_params
    value = params[:term]
    type = params[:option]
    s_books = Settings.static_page.search_book
    s_author = Settings.static_page.search_author
    s_category = Settings.static_page.search_category

    return Book.search_by_book_title(value) if type == s_books

    return Book.search_by_author_name(value) if type == s_author

    return Book.search_by_category_name(value) if type == s_category

    Book.order_by_title
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_book.html.erb
<div class="col-sm-3" >
  <div class="product-card">
    <div class="badge"><%= t(".new") %></div>
    <div class="product-tumb">
      <img src=<%= book.image %> alt="">
    </div>
    <div class="product-details">
      <span class="product-catagory"><%= book.author_name %> | <%= book.category_name %></span>
      <h5 class="text-h5"><%= link_to book.title, book_path(book.id) %></a></h5>
      <p class="text-h6"><%= book.description %></p>
      <div class="product-bottom-details row">
        <% if !@current_user.nil? %>
        <%= link_to t(".borrow"), new_user_borrowing_book_path(@current_user.id, id: book.id),
         class: "btn btn-primary button", style: "width: 100%; margin-bottom: 1px" %>
         <% else %>
         <%= link_to t(".borrow"), sessions_login_path,
         class: "btn btn-primary button", style: "width: 100%; margin-bottom: 1px" %>
         <% end %>
        <%= link_to t(".details"),book_path(book.id), class: "btn btn-info" ,style: "width: 100% ; margin-bottom: 5px" %>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/_productCrad.html.erb
<% for i in (1..3) %>
<div class="row">
  <% for i in (1..4) %>
  <div class="col-sm-3" >
    <div class="product-card">
      <div class="badge">Hot</div>
      <div class="product-tumb">
        <img src="https://www.dtv-ebook.com/images/files_2/2020/ban-that-ba-dao!-jen-sincero.jpg" alt="">
      </div>
      <div class="product-details">
        <span class="product-catagory">Women,bag</span>
        <h4><a href="">Bạn thật bá đạo</a></h4>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero, possimus nostrum!</p>
        <div class="product-bottom-details row">
          <button type="button" class="btn btn-primary"
            style="width: 100% ; margin-bottom: 5px">Borrow</button>
          <button type="button" class="btn btn-info"
          style="width: 100%">Details</button>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>
<% end %>

app/views/static_pages/_slide.html.erb
<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel" style="padding: 20px 50px 50px 50px; ">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag "anhsach1.jpg" , class: "d-block w-100" , alt: "..." %>
      <div class="carousel-caption d-none d-md-block">
        <h5>First slide label</h5>
        <p>Some representative placeholder content for the first slide.</p>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag "anhsach2.jpg" , class: "d-block w-100" ,alt: "..." %>
      <div class="carousel-caption d-none d-md-block">
        <h5>Second slide label</h5>
        <p>Some representative placeholder content for the second slide.</p>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag "anhsach3.jpg" , class: "d-block w-100" ,alt: "..." %>
      <div class="carousel-caption d-none d-md-block">
        <h5>Third slide label</h5>
        <p>Some representative placeholder content for the third slide.</p>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<%= render "static_pages/slide" %>

<div class="row">
  <%= render partial: "static_pages/book", collection: @abc %>
  <ul class="pagination">
   <%= will_paginate @abc, previous_label: "&#8592;", next_label: "&#8594;" %>
  </ul>
</div>

app/views/static_pages/list_books.html.erb
<div class="container-fuild list-book" style="margin-top: 30px">
  <div class = "row box-book">
    <div class="col-lg-2 col-md-2 menu-book" style="overflow: auto; ">
     <!--  <div class="btn btn-primary task" > All book</div>
      <div class="btn btn-primary task" > Truyện tranh</div>
      <div class="btn btn-primary task" > Truyện chữ </div>
      <div class="btn btn-primary task" > Sách thiếu nhi </div> -->
      <% @categories.each do |c| %>
       <div class="btn btn-primary task" > <%= c.name %></div>
      <% end %>
    </div>
    <div class="col-lg-10 col-md-10 show-book">
      <%= form_tag(static_pages_list_books_path, method: :get) do %>
      <div class="row">
        <%= text_field_tag :term, params[:term], class: "form-control mr-sm-2" , style:"width: 56% ; margin-left: 20px" %>
        <%= select_tag :option, options_for_select([[t(".all_book"),"books"] ,[t(".author"),"author"] ,[t(".category"),"category"] ], params[:option]),class: "form-control",style: "width: 20%; margin-right: 5px" %>
        <%= submit_tag t(".search") , class: "btn btn-outline-success my-2 my-sm-0" ,style:"width: 20%" %>
      </div>
      <% end %>
      <div class="row">

       <%= render partial: "static_pages/book", collection: @books %>
         <ul class="pagination">
          <%= will_paginate @books, previous_label: "&#8592;", next_label: "&#8594;" %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/view_all_book.html.erb
<div class = " btn btn-dannger" >
  Xin chao
</div>