config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en|vi/ do
    resources :books
    root to: "static_pages#home"
    get "static_pages/list_books"
    get "sessions/login"
    post "sessions/login" ,to: "sessions#create"
    delete "sessions/logout", to: "sessions#destroy"
    get "sessions/sign_up"

    resources :users do
        resources :borrowing_books
    end

    namespace :admin do
        root to:
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :category
  belongs_to :publisher
  belongs_to :author
  delegate :name, to: :author, prefix: true
  delegate :name, to: :category, prefix: :category

  has_many :borrowing_books, dependent: :nullify

  scope :search_by_book_title,
        ->(term){where("title LIKE ?", "%#{term}%")}

  scope :search_by_author_name,
        ->(term){joins(:author).where(" authors.name LIKE ?", "%#{term}%")}

  scope :search_by_category_name,
        ->(term){joins(:category).where("categories.name LIKE ?", "%#{term}%")}
  scope :order_by_title, ->{(order :title).includes(:author, :category)}

  def update_quantity updated_quantity
    update!(quantity: updated_quantity)
  end
end

app/models/book_interaction.rb
class BookInteraction < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/borrowing_book.rb
class BorrowingBook < ApplicationRecord
  belongs_to :user
  belongs_to :book
  delegate :name, to: :user, prefix: :user
  delegate :title, to: :book, prefix: :book

  validates :borrowed_date, :expiration_date, presence: true

  validate :expiration_date_range

  enum status: {pending: 0, approved: 1, canceled: 2, rejected: 3}

  scope :order_by_created_date, ->{order :created_at}

  scope :where_cur_user_deleted, ->(id){where(user_id: id).where(deleted: 0)}

  class << self
    def statuses_i18n
      statuses.each_with_object({}) do |(k, _), obj|
        obj[I18n.t("borrowing_book.status.#{k}")] = k
      end
    end
  end

  def status_i18n
    I18n.t("borrowing_book.status.#{status}")
  end

  private

  def expiration_date_range
    return if expiration_date.blank?

    if expiration_date < borrowed_date
      errors.add :expiration_date, I18n.t("must_be_after_borrowed_date")
    elsif expiration_date > borrowed_date + 30.days
      errors.add :expiration_date,
                 I18n.t("not_more_than_30_days_from_the_borrowed_date")
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/follow_author.rb
class FollowAuthor < ApplicationRecord
  belongs_to :author
  belongs_to :user
end

app/models/publisher.rb
class Publisher < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :borrowing_books, dependent: :nullify
  has_secure_password

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale
  before_action :current_user

  include SessionsHelper

  private

  def default_url_options
    {locale: I18n.locale}
  end

  def set_locale
    locale = params[:locale].to_s.strip.to_sym
    return I18n.locale = locale if I18n.available_locales.include?(locale)

    I18n.locale = I18n.default_locale
  end
end

app/controllers/book_controller.rb
class BookController < ApplicationController
  def index
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :load_book
  before_action :current_user

  def show; end

  def load_book
    @book = Book.find_by id: params[:id]
    return if @book
    redirect_to root_path
    flash[:success] = "Không tìm thấy trang 404"
  end
end

app/controllers/borrowing_book_controller.rb
class BorrowingBookController < ApplicationController
  before_action :current_user

  def index
    @borrowing_books = @current_user.borrowing_books.order_by_created_date
                                    .paginate(page: params[:page],
                                     per_page: Settings.static_page.per_page)
  end
end

app/controllers/borrowing_books_controller.rb
class BorrowingBooksController < ApplicationController
  before_action :load_book, :check_quantity_zero, only: :new

  before_action :check_book, :check_quantity_book, :borrowed_book,
                :book_out_of_date, only: :create

  def new
    @borrowing_book = @current_user.borrowing_books.new
  end

  def index
    @borrowing_books =
      @current_user.borrowing_books.includes(:book).where(deleted: 0)
                   .order_by_created_date
                   .paginate(page: params[:page],
                   per_page: Settings.borrowing_book_controller.per_page)
  end

  def create
    @borrowing_book = @current_user.borrowing_books.new borrowing_book_params
    sent_request_success
  end

  private

  def check_quantity_book
    return if @current_user.borrowing_books.where(deleted: 0).count < 5

    flash[:danger] = t "over_quantity_to_borrow"
    redirect_to root_path
  end

  def borrowed_book
    return unless @current_user.borrowing_books.where(deleted: 0)
                               .pluck(:book_id)
                               .include? params[:borrowing_book][:book_id].to_i

    flash[:danger] = t "borrowed_book"
    redirect_to root_path
  end

  def load_book
    @book = Book.find_by id: params[:id]
    return if @book

    flash[:danger] = t "error_find_book"
    redirect_to root_path
  end

  def book_out_of_date
    @current_user.borrowing_books.each do |b|
      if b.expiration_date < Date.current + 1.day
        flash[:danger] = t "book_out_of_date"
        redirect_to root_path
      end
    end
  end

  def check_book
    @book = Book.find_by id: params[:borrowing_book][:book_id]
    return if @book

    flash[:danger] = t "error_find_book"
    redirect_to root_path
  end

  def sent_request_success
    ActiveRecord::Base.transaction do
      @borrowing_book.save!
      updated_quantity = @book.quantity - 1
      @book.update_quantity(updated_quantity)
      flash[:success] = t "request_sent_successfully"
      redirect_to root_path
    end
  rescue ActiveRecord::RecordInvalid
    flash.now[:danger] = t "request_sent_failed"
    render :new
  end

  def borrowing_book_params
    params.require(:borrowing_book).permit :borrowed_date,
                                           :expiration_date, :book_id
  end

  def check_quantity_zero
    return unless @book.quantity.zero?

    flash[:warning] = "book_out_of_stock"
    redirect_to root_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by email: params[:session][:email].downcase
    if user && (user.authenticate params[:session][:password])
      log_in user
      current_user
      redirect_to root_path
      flash[:success] = "login success"
    else
      flash.now[:danger] = "invalid_email_password_combination"
      render :login
    end
  end

  def sign_up; end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :current_user

  def home
    @abc = Book.order_by_title
                 .paginate(page: params[:page],
                  per_page: Settings.static_page.per_page)
  end

  def list_books
    @categories = Category.all
    @books = check_params.includes(:author, :category)
                         .paginate(page: params[:page],
                          per_page: Settings.static_page.per_page)
    if @books.empty?
      flash[:info] = "Không tìm thấy sách #{params[:term]}"

    end
  end

  private

  def check_params
    value = params[:term]
    type = params[:option]
    s_books = Settings.static_page.search_book
    s_author = Settings.static_page.search_author
    s_category = Settings.static_page.search_category

    return Book.search_by_book_title(value) if type == s_books

    return Book.search_by_author_name(value) if type == s_author

    return Book.search_by_category_name(value) if type == s_category

    Book.order_by_title
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    base_title = t("base_title")
    page_title.blank? ? base_title : "#{page_title} | #{base_title}"
  end
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def sign_up; end

  def current_user
    @current_user ||= User.find_by id: session[:user_id]
  end

  def logged_in?
    current_user.present?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_contact.html.erb
<div class="footer-dark">
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-md-3 item">
                    <h3>Services</h3>
                    <ul>
                        <li><a href="#">Web design</a></li>
                        <li><a href="#">Development</a></li>
                        <li><a href="#">Hosting</a></li>
                    </ul>
                </div>
                <div class="col-sm-6 col-md-3 item">
                    <h3>About</h3>
                    <ul>
                        <li><a href="#">Company</a></li>
                        <li><a href="#">Team</a></li>
                        <li><a href="#">Careers</a></li>
                    </ul>
                </div>
                <div class="col-md-6 item text">
                    <h3>Company Name</h3>
                    <p>Praesent sed lobortis mi. Suspendisse vel placerat ligula. Vivamus ac sem lacus. Ut vehicula rhoncus elementum. Etiam quis tristique lectus. Aliquam in arcu eget velit pulvinar dictum vel in justo.</p>
                </div>
                <div class="col item social"><a href="#"><i class="icon ion-social-facebook"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-instagram"></i></a></div>
            </div>
            <p class="copyright">Company Name © 2018</p>
        </div>
    </footer>
</div>

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
  <div class="alert alert-danger">
    <%= t(".the_form_contains") %><%= pluralize object.errors.count, "error" %>.
  </div>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li style="color: red"><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/layouts/_flash_msg.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>" style="margin-top: 20px">
    <%= message %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer-dark">
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-md-3 item">
                    <h3>Services</h3>
                    <ul>
                        <li><a href="#">Web design</a></li>
                        <li><a href="#">Development</a></li>
                        <li><a href="#">Hosting</a></li>
                    </ul>
                </div>
                <div class="col-sm-6 col-md-3 item">
                    <h3>About</h3>
                    <ul>
                        <li><a href="#">Company</a></li>
                        <li><a href="#">Team</a></li>
                        <li><a href="#">Careers</a></li>
                    </ul>
                </div>
                <div class="col-md-6 item text">
                    <h3>Company Name</h3>
                    <p>Praesent sed lobortis mi. Suspendisse vel placerat ligula. Vivamus ac sem lacus. Ut vehicula rhoncus elementum. Etiam quis tristique lectus. Aliquam in arcu eget velit pulvinar dictum vel in justo.</p>
                </div>
                <div class="col item social"><a href="#"><i class="icon ion-social-facebook"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-instagram"></i></a></div>
            </div>
            <p class="copyright">Company Name © 2018</p>
        </div>
    </footer>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="sticky; z-index: 1000; top: 0 ;position: fixed; width: 100%">

  <b class="navbar-brand" href="#"><%= t(".library") %></b>

  <button class="navbar-toggler" type="button" data-toggle="collapse"
  data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto">

    <%= link_to t(".home") , root_path , class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to t(".books") , static_pages_list_books_path , class: "nav-link" %>
  </li>

  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown"
    role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

    <%= t(".categories") %>
  </a>
  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
    <a class="dropdown-item" href="#">Action</a>
    <a class="dropdown-item" href="#">Another action</a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="#">Something else here</a>
  </div>
</li>

<li class="nav-item">
  <li class="nav-link"><%= link_to t(".en"), locale: :en %></li>
  <li class="nav-link"><%= link_to t(".vi"), locale: :vi %></li>
</li>
</ul>

<form class="form-inline my-2 my-lg-0">
  <input class="form-control mr-sm-2" type="search"
  placeholder= <%= t(".search") %>  aria-label="Search">
  <button class="btn btn-outline-success my-2 my-sm-0"
  type="submit"> <%= t(".search") %> </button>
</form>

<ul  class="navbar-nav my-2 my-lg-0 " style="margin-left: 30px">
  <% if logged_in? %>
  <li class="nav-item" style="margin-right: 5px">
    <%= link_to t(".borrowing_book"), user_borrowing_books_path(@current_user.id),
    class: "nav-link  btn btn-info" %>
  </li>

  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle btn btn-success" href="#" id="navbarDropdown"
    role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

    <%= @current_user.name  %>
  </a>
  <div class="dropdown-menu dropdown-menu-lg-right" aria-labelledby="navbarDropdown">
    <a class="dropdown-item" href="#"><%= t(".profile") %></a>
    <a class="dropdown-item" href="#"><%= t(".setting") %></a>
    <div class="dropdown-divider"></div>
    <%= link_to t(".log_out"), sessions_logout_path, method: :delete, class:"dropdown-item"%></a>
  </div>
</li>

<% else %>
<li class="nav-item">
  <%= link_to t(".login") , sessions_login_path , class: "nav-link btn btn-success", style: "width: 110px ; color: white" %>
</li>

<li class="nav-item">
  <%= link_to t(".sign_up") , sessions_sign_up_path , class: "nav-link btn btn-danger", style: "margin-left: 5px; width: 110px; color: white" %>
</a>
</li>
<% end %>

</ul>
</div>
</nav>

app/views/layouts/admin_page.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title yield :title %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_pack_tag "admin", "data-turbolinks-track": "reload" %>
  <%= javascript_pack_tag "admin", "data-turbolinks-track": "reload" %>
</head>

<body>
  <%= render "layouts/header" %>
  <div class="container-fluid" style="padding-top: 50px; margin-bottom: 20px">
    <%= render "layouts/flash_msg" , collection: @flash %>
    <%= yield %>
  </div>
  <%= render "layouts/footer" %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title yield :title %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_pack_tag "application", "data-turbolinks-track": "reload" %>
  <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
</head>

<body>
  <%= render "layouts/header" %>
  <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <div class="container-fluid">
    <%= render "layouts/flash_msg" , collection: @flash %>
    <%= yield %>
  </div>
  <%= render "layouts/footer" %>
</body>
</html>